import pandas as pd
import matplotlib.pyplot as plt

full_1_data = pd.read_csv('full_1.csv', skiprows=5)
full_2_data = pd.read_csv('full_2.csv', skiprows=5)
heat_1_data = pd.read_csv('heat_1.csv', skiprows=5)
heat_2_data = pd.read_csv('heat_2.csv', skiprows=5)
temp_1_data = pd.read_csv('temp_1.csv', skiprows=5)
temp_2_data = pd.read_csv('temp_2.csv', skiprows=5)

plt.scatter(full_1_data.iloc[:, 3], full_1_data.iloc[:, 1], label='Cопряженная, x=0.1L')
plt.scatter(full_2_data.iloc[:, 3], full_2_data.iloc[:, 1], label='Cопряженная, x=0.9L')
plt.scatter(heat_1_data.iloc[:, 3], heat_1_data.iloc[:, 1], label='Несопряженная q, x=0.1L')
plt.scatter(heat_2_data.iloc[:, 3], heat_2_data.iloc[:, 1], label='Несопряженная q, x=0.9L')
plt.scatter(temp_1_data.iloc[:, 3], temp_1_data.iloc[:, 1], label='Несопряженная T, x=0.1L')
plt.scatter(temp_2_data.iloc[:, 3], temp_2_data.iloc[:, 1], label='Несопряженная T, x=0.9L')
plt.ylabel('y, м')
plt.xlabel('T, K')
plt.grid(True)
plt.legend()
plt.show()

plt.scatter(full_1_data.iloc[:, 4], full_1_data.iloc[:, 1], label='Cопряженная, x=0.1L')
plt.scatter(full_2_data.iloc[:, 4], full_2_data.iloc[:, 1], label='Cопряженная, x=0.9L')
plt.scatter(heat_1_data.iloc[:, 4], heat_1_data.iloc[:, 1], label='Несопряженная q, x=0.1L')
plt.scatter(heat_2_data.iloc[:, 4], heat_2_data.iloc[:, 1], label='Несопряженная q, x=0.9L')
plt.scatter(temp_1_data.iloc[:, 4], temp_1_data.iloc[:, 1], label='Несопряженная T, x=0.1L')
plt.scatter(temp_2_data.iloc[:, 4], temp_2_data.iloc[:, 1], label='Несопряженная T, x=0.9L')
plt.ylabel('y, м')
plt.xlabel('V, м/с')
plt.grid(True)
plt.legend()
plt.show()

plt.scatter(full_1_data.iloc[:, 5], full_1_data.iloc[:, 1], label='Cопряженная, x=0.1L')
plt.scatter(full_2_data.iloc[:, 5], full_2_data.iloc[:, 1], label='Cопряженная, x=0.9L')
plt.scatter(heat_1_data.iloc[:, 5], heat_1_data.iloc[:, 1], label='Несопряженная q, x=0.1L')
plt.scatter(heat_2_data.iloc[:, 5], heat_2_data.iloc[:, 1], label='Несопряженная q, x=0.9L')
plt.scatter(temp_1_data.iloc[:, 5], temp_1_data.iloc[:, 1], label='Несопряженная T, x=0.1L')
plt.scatter(temp_2_data.iloc[:, 5], temp_2_data.iloc[:, 1], label='Несопряженная T, x=0.9L')
plt.ylabel('y, м')
plt.xlabel('U, м/с')
plt.grid(True)
plt.legend()
plt.show()
